# Generated by Django 3.2.3 on 2021-07-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210719_1744'),
        ('app', '0004_product_categoria'),
    ]

    operations = [
    ]
